export enum status {
  PREPARING = 'PREPARING',
  PLACED = 'PLACED',
  ACCEPTED = 'ACCEPTED',
  DISPATCHED = 'DISPATCHED',
  CANCELLED = 'CANCELLED',
  DELIVERED = 'DELIVERED',
  DECLINED = 'DECLINED',
}
